export const DC_API_BASE_URL = "https://api.datacommons.org/";

export const INDEX_VARIABLE_NAME_STATE = "state";
export const INDEX_VARIABLE_NAME_COUNTY = "county";
export const INDEX_VARIABLE_NAME_CITY = "city";
export const INDEX_VARIABLE_NAME_ZIP_CODE = "zip code";
export const INDEX_VARIABLES = [INDEX_VARIABLE_NAME_STATE, INDEX_VARIABLE_NAME_COUNTY, INDEX_VARIABLE_NAME_CITY, INDEX_VARIABLE_NAME_ZIP_CODE];
export const INDEX_VARIABLE_NAME_DEFAULT = INDEX_VARIABLE_NAME_ZIP_CODE;

export const NOT_AVAILABLE_VALUE = "NA";